files:
  - source: /typo3/sysext/*/Resources/Private/Language/
    translation: '%original_path%/%two_letters_code%.%original_file_name%'
    ignore: /typo3/sysext/core/Resources/Private/Language/Iso/
